# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     redcarpet
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
title: 朱旦奇
subTitle: zhudanqi888@gmail.com
url: http://zhudanqi.github.io
#url: http://localhost:4000/
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 标签分类
    url: /categories.html
  - text: 关于我
    url: /contact.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
#  - item: /themes/violet/images/hdbg02.jpg
 # - item: /themes/violet/images/hdbg03.jpg
 # - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-github
    url: http://github.com/zhu-dq
  - class: fa-weibo
    url: http://weibo.com/2401226655

#作者信息
author:
  name: Danqi Zhu
  email: zhudanqi888@gmail.com
  link: http://zhudanqi.github.io
  weibo: http://weibo.com/2401226655
  github: http://github.com/zhu-dq
  img: /images/me.jpg

#评论信息
disqus:
  config: true
  id: zhudanqi

duoshuo:
  config: false
  id: zhudanqi